### PR TITLE
:hammer_and_wrench: @feature/linters

### PR DESCRIPTION
**Pull request by mahabubx7**
### :hammer_and_wrench: @feature/linters
:heavy_check_mark: Added `Github Action` workflows for lining.
:heavy_check_mark: Fixed CSS according to linters.

### CODE REVIEW

**Comment by mahabubx7** [comment]
### Good work! You did it! :boom:
gif
:heavy_check_mark: Everything is alright.

##### **Approved!** :heavy_check_mark:

**Comment by mahabubx7** [comment]
### Good work! You did it! :boom:
gif
:heavy_check_mark: Everything is alright.

##### **Approved!** :heavy_check_mark:

**Comment by andgarzonmal** [comment]
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️


 Hi @mahabubx7 ✋🏼 

#### Your project is excellent. You are almost done. However, there are some issues you should fix. Please fix them and your project will be approved.

___ 

### 💯  Highlights 💯
- Nice job reviewing your project

### ♻️ Request changes ♻️

- [ ] Please add at least one in line comment on your review, see how to do so [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md) 
___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### Cheers and Happy coding! 💻 👏
almost


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by mahabubx7** [comment]
:recycle: please re-review this.
:ballot_box_with_check: I have updated that.

**Review by joel-kalema — COMMENTED** [review]
Hi @mahabubx7 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑  

- [ ] You have submitted a project that was already merged


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @joel-kalema in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
